### PR TITLE
[FIX] Duplicate ParameterTypes per ElementDefinition; fixes #269

### LINKED ISSUE #269: [FIX] Duplicate ParameterTypes on an ElementDefinition should not be created
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
@MartinFijneman  was able to create a duplicate parameter in an ElementDefinition from an end-user app. The server should prevent this from happening. Therefore the integration test suite needs to be extended to validate for each kind of ParameterType that a duplicate **cannot** be created. The following scenario's are requried:

  - in 2 separate transactions try to create a Parameter with the same ParameterType in the same ElementDefinition
  - in 1 transaction try to create 2 distinct Parameters that reference the same ParameterType in the same ElementDefinition

### System Configuration

- COMET Web Services version: 7.1.1

### PR DESCRIPTION
**Pull request by lxatrhea**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WebServices-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
[FIX] Duplicate ParameterTypes per ElementDefinition; fixes #269

### CODE REVIEW

**Review by antoineatrhea — APPROVED** [review]

File: CometServer/Services/Operations/SideEffects/Implementation/ParameterSideEffect.cs [hunk 1]
```diff
@@ -74,6 +77,16 @@ public sealed class ParameterSideEffect : OperationSideEffect<Parameter>
...
 
+        /// <summary>
+        /// Gets or sets the <see cref="IParameterService"/>
+        /// </summary>
+        public IParameterService ParameterService { get; set; }
+
+        /// <summary>
+        /// Gets or sets the <see cref="IParameterTypeService"/>
+        /// </summary>
+        public IParameterTypeService ParameterTypeService { get; set; }
```
Comment (samatrhea) [inline CometServer/Services/Operations/SideEffects/Implementation/ParameterSideEffect.cs:88]: i think you should be using `ICachedReferenceDataService` and `CachedReferenceDataService`

**Review by samatrhea — CHANGES_REQUESTED** [review]
