### PR TITLE
Fix #75 SQL scripts without Views/Functions and cleanup migration

### LINKED ISSUE #75: generate SQL tables based on dotliquid code generator
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
All code generators need to make use of dotliquid. The SQL generator for CDP4 needs to be migrated from T4 to dotliquid templates

- [x] convert current SQL to expected SQL files in code generator project
- [x] create dotliquid templates to generate the expected SQL

### Steps to Reproduce
NA

### System Configuration
NA

### PR DESCRIPTION
**Pull request by antoineatrhea**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WebServices-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

Fix #75 

- SQL scripts generated with DotLiquid
- Dao missed some column on SELECT query when a class is contained but is not directly contained (superclass is contained)
- SQL Scripts do not contains any views/data function anymore 
- Migration Script that removes all existing VIEWS/Data function

Remarks : SqlMetadataHelper class may not be necessary but could be useful later, for any SELECT query that may need to be handcoded

### CODE REVIEW

**Review by lxatrhea — COMMENTED** [review]
Why did the "*_20210109*" Migrations change?

**Comment by antoineatrhea** [comment]
@lxatrhea I moved old migrations (with views) onto another folder and just removed views/function from there. I did not change name of migration to not rerun them if already applied

**Review by lxatrhea — APPROVED** [review]

File: CDP4Orm/MigrationScript/EngineeringModel_20210109_6_4_0_0_Model_Updates.sql [hunk 1]
```diff
@@ -1,4 +1,4 @@
-﻿-- Create table for class LogEntryChangelogItem (which derives from: Thing)
+-- Create table for class LogEntryChangelogItem (which derives from: Thing)
```
Comment (samatrhea) [inline CDP4Orm/MigrationScript/EngineeringModel_20210109_6_4_0_0_Model_Updates.sql:1]: am i to understand that you are changing existing migrations?

File: CDP4Orm/MigrationScript/Iteration_20210109_6_5_0_0_Model_Updates.sql [hunk 2]
```diff
@@ -1,4 +1,4 @@
-﻿-- OrganizationalParticipant is a collection property (many to many) of class ElementDefinition: [0..*]-[1..1]
+-- OrganizationalParticipant is a collection property (many to many) of class ElementDefinition: [0..*]-[1..1]
```
Comment (samatrhea) [inline CDP4Orm/MigrationScript/Iteration_20210109_6_5_0_0_Model_Updates.sql:1]: am i to understand that you are changing existing migrations?

File: CometServer/Helpers/Cdp4TransactionManager.cs [hunk 3]
```diff
@@ -418,11 +418,12 @@ private static void ApplyIterationContext(NpgsqlTransaction transaction, string
             }
             
             var sqlBuilder = new StringBuilder();
```
Comment (samatrhea) [inline CometServer/Helpers/Cdp4TransactionManager.cs:420]: here i would like an explanation in a conversation

File: CDP4Orm/AutoGenOrmHelpers/DaoResolver.cs [hunk 4]
```diff
@@ -0,0 +1,226 @@
...
+        /// <summary>
+        /// Gets the <see cref="Dictionary{TKey,TValue}" /> that can provides
+        /// </summary>
+        private readonly Dictionary<string, Func<IDao>> existingDaos;
+
+        /// <summary>
+        /// Initializes a new <see cref="DaoResolver" />
+        /// </summary>
+        /// <param name="serviceProvider">The injected <see cref="IServiceProvider" /></param>
+        public DaoResolver(IServiceProvider serviceProvider)
```
Comment (samatrhea) [inline CDP4Orm/AutoGenOrmHelpers/DaoResolver.cs:54]: using serviceprovider.GetService is an anti-pattern https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines

i propose that instead we inject them as properties these services and that there is a helper function that returns the value of the property

File: CDP4Orm/Dao/Resolve/ContainerDao.cs [hunk 5]
```diff
@@ -207,18 +216,20 @@ public class ContainerDao : IContainerDao
                 otherPartition = partition.Replace(Utils.IterationSubPartition, Utils.EngineeringModelPartition);
             }
 
+            var dao = this.DaoResolver.QueryDaoByTypeName(typeName);
+            
             sqlBuilder.Append(
```
Comment (samatrhea) [inline CDP4Orm/Dao/Resolve/ContainerDao.cs:221]: may i request we refactor this so it becomes more readable. using the numbered arguments and a combi of string builder and string.format can be improved

File: CDP4Orm/Dao/Resolve/ResolveDao.cs [hunk 6]
```diff
@@ -86,8 +86,8 @@ private static IEnumerable<ResolveInfo> ReadSiteDirectoryThing(NpgsqlTransaction
 
             // get all Thing 'concepts' that are newer then passed in revision
             sqlBuilder.Append(
-                "SELECT \"ValueTypeSet\"-> 'ClassKind' as \"TypeInfo\", \"Iid\"").Append(
-                " FROM \"{0}\".\"Thing_View\"").Append(
+                "SELECT \"ValueTypeDictionary\"-> 'ClassKind' as \"TypeInfo\", \"Iid\"").Append(
```
Comment (samatrhea) [inline CDP4Orm/Dao/Resolve/ResolveDao.cs:89]: may i request we refactor this so it becomes more readable. using the numbered arguments and a combi of string builder and string.format can be improved

**Review by samatrhea — CHANGES_REQUESTED** [review]

File: CDP4Orm/MigrationScript/EngineeringModel_20210109_6_4_0_0_Model_Updates.sql (hunk 1 above)
Comment (alexatrhea) [reply CDP4Orm/MigrationScript/EngineeringModel_20210109_6_4_0_0_Model_Updates.sql:1]: no, i think he copied the old ones unmodified to Old_WithViews folder and made a new set here by modifying the old ones. However @antoineatrhea I also don't get exactly why this is needed?

**Review by alexatrhea — COMMENTED** [review]
yeah maybe we can have a quick chat on the migrations to understand.

File: CDP4Orm/MigrationScript/EngineeringModel_20210109_6_4_0_0_Model_Updates.sql (hunk 1 above)
Comment (antoineatrhea) [reply CDP4Orm/MigrationScript/EngineeringModel_20210109_6_4_0_0_Model_Updates.sql:1]: I kept the old ones to have a traceability. But it's required to still have those migrations since the structure is on version 1.1.27, so we have to apply model updates migration. However, I can not keep the exact same as before since we don't have VIEWS and Data functions anymore. I added a new migration that cleans every VIEWS and Data functions to be sure to not have of them if we have an old database

File: CDP4Orm/AutoGenOrmHelpers/DaoResolver.cs (hunk 4 above)
Comment (antoineatrhea) [reply CDP4Orm/AutoGenOrmHelpers/DaoResolver.cs:54]: Should we inject them with a Lazy process? otherwise, at anytime we request DaoResolver, it would also initialize all Dao, no? With the IServiceProvider, we only request them when invoking the method?

File: CDP4Orm/Dao/Resolve/ResolveDao.cs (hunk 6 above)
Comment (antoineatrhea) [reply CDP4Orm/Dao/Resolve/ResolveDao.cs]: refactored

File: CDP4Orm/Dao/Resolve/ContainerDao.cs (hunk 5 above)
Comment (antoineatrhea) [reply CDP4Orm/Dao/Resolve/ContainerDao.cs]: refactored

**Review by samatrhea — APPROVED** [review]
